--
-- PostgreSQL database dump
--

\restrict KvytyS4b8dUBVBtSaxH0R9Utnvel5A4NUgwbesDSJuQ8o7MftupEA588xypkEpQ

-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO admin;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO admin;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO admin;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO admin;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO admin;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO admin;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO admin;

--
-- Name: product_category; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.product_category (
    id bigint CONSTRAINT book_category_id_not_null NOT NULL,
    choice character varying(100) CONSTRAINT book_category_choice_not_null NOT NULL
);


ALTER TABLE public.product_category OWNER TO admin;

--
-- Name: book_category_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.product_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.cart OWNER TO admin;

--
-- Name: cart_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_item; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.cart_item (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT cart_item_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.cart_item OWNER TO admin;

--
-- Name: cart_item_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.cart_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO admin;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO admin;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO admin;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO admin;

--
-- Name: order_item; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.order_item (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT order_item_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.order_item OWNER TO admin;

--
-- Name: order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.order_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    order_number character varying(30) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.orders OWNER TO admin;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_details; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.product_details (
    id bigint CONSTRAINT product_book_details_id_not_null NOT NULL,
    isbn character varying(20) CONSTRAINT product_book_details_isbn_not_null NOT NULL,
    title character varying(255) CONSTRAINT product_book_details_title_not_null NOT NULL,
    author character varying(255) CONSTRAINT product_book_details_author_not_null NOT NULL,
    description text CONSTRAINT product_book_details_description_not_null NOT NULL,
    price numeric(10,2) CONSTRAINT product_book_details_price_not_null NOT NULL,
    publication_year integer CONSTRAINT product_book_details_publication_year_not_null NOT NULL,
    image character varying(100),
    total_copies integer CONSTRAINT product_book_details_total_copies_not_null NOT NULL,
    available_copies integer CONSTRAINT product_book_details_available_copies_not_null NOT NULL,
    is_active boolean CONSTRAINT product_book_details_is_active_not_null NOT NULL,
    created_at timestamp with time zone CONSTRAINT product_book_details_created_at_not_null NOT NULL,
    updated_at timestamp with time zone CONSTRAINT product_book_details_updated_at_not_null NOT NULL,
    category_id bigint CONSTRAINT product_book_details_category_id_not_null NOT NULL,
    pdf character varying(100),
    CONSTRAINT product_book_details_available_copies_check CHECK ((available_copies >= 0)),
    CONSTRAINT product_book_details_total_copies_check CHECK ((total_copies >= 0))
);


ALTER TABLE public.product_details OWNER TO admin;

--
-- Name: product_book_details_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.product_details ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_book_details_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add order	9	add_order
26	Can change order	9	change_order
27	Can delete order	9	delete_order
28	Can view order	9	view_order
29	Can add product book details	12	add_productbookdetails
30	Can change product book details	12	change_productbookdetails
31	Can delete product book details	12	delete_productbookdetails
32	Can view product book details	12	view_productbookdetails
33	Can add cart management	8	add_cartmanagement
34	Can change cart management	8	change_cartmanagement
35	Can delete cart management	8	delete_cartmanagement
36	Can view cart management	8	view_cartmanagement
37	Can add product book category	11	add_productbookcategory
38	Can change product book category	11	change_productbookcategory
39	Can delete product book category	11	delete_productbookcategory
40	Can view product book category	11	view_productbookcategory
41	Can add order item	10	add_orderitem
42	Can change order item	10	change_orderitem
43	Can delete order item	10	delete_orderitem
44	Can view order item	10	view_orderitem
45	Can add cart item	7	add_cartitem
46	Can change cart item	7	change_cartitem
47	Can delete cart item	7	delete_cartitem
48	Can view cart item	7	view_cartitem
49	Can add Token	13	add_token
50	Can change Token	13	change_token
51	Can delete Token	13	delete_token
52	Can view Token	13	view_token
53	Can add Token	14	add_tokenproxy
54	Can change Token	14	change_tokenproxy
55	Can delete Token	14	delete_tokenproxy
56	Can view Token	14	view_tokenproxy
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
4	pbkdf2_sha256$1500000$pXUt54yd0CwBEMQamoDmJJ$zeUyEdnULVghkC0NkcHWhskpBv/MqygSVPSvhrcZaB4=	2026-09-24 21:11:37.441436+00	f	krishna123	krishna	pada	krishnamondal11234@gmail.com	f	t	2026-09-24 21:10:32.934862+00
3	pbkdf2_sha256$1500000$CAUezgImtjvI9jViIi3Jb8$4m8TBoqOH2XFbQS7f4qH/GDCfD+Knoiu4IjyObKDHsA=	\N	t	sonu	sonu	mondal	sonumandal0987@gmail.com	t	t	2026-09-24 20:21:46.643423+00
2	pbkdf2_sha256$1500000$QrBeXF0NazhgW26juazpac$3BTqLDjlalD/djkhiEG8Ns01qpq3fkcaSTKldRgaGVo=	2026-09-25 06:08:24.006924+00	f	arun123	arun	mondal	arun@gmail.com	f	t	2026-09-23 11:43:28.690954+00
1	pbkdf2_sha256$1500000$3HUvNfT7M7MJ8H5dREUWrQ$4PJ0q37CT4/9LTLuhQasVCvRI/NTAB5scXZbP1vNMGc=	2026-09-25 06:12:14.365833+00	t	test	test	dummy	test@gmail.com	t	t	2026-09-23 11:11:01.396972+00
5	pbkdf2_sha256$1500000$i0D2SK4l3JxfLfydmc1SSA$iya2pPvB6RyzgIu9Qj7pSvYqEAUglhuMNxnT+JDmVkU=	\N	f	hari	Hari	Mondal	hari@gmail.com	f	t	2026-09-25 11:18:49.637778+00
6	pbkdf2_sha256$1500000$OXep1jAbj5r7CAApEPbrJ9$+8ZPqszny/b0QkNl2GTPJYtiEFPbV9gDRFgLWVZQfgU=	2026-09-25 11:50:44.121175+00	t	hari5112	hiranmay	mondal	hiranmaymondal258@gmail.com	t	t	2026-09-25 11:49:49.638952+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
273103a1445165696da17240d5dcd9334c0637c8	2026-09-24 15:39:53.331218+00	2
ff05b3e67fd182f79b2d5b3b2a11e28b7f80299e	2026-09-24 15:47:44.655477+00	1
c23246afe16f82b573c6baee4746da627849ec05	2026-09-25 11:18:49.974284+00	5
\.


--
-- Data for Name: cart; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.cart (id, created_at, updated_at, user_id) FROM stdin;
1	2026-09-24 07:55:19.788882+00	2026-09-24 07:55:19.788904+00	1
2	2026-09-24 09:58:58.608602+00	2026-09-24 09:58:58.608614+00	2
\.


--
-- Data for Name: cart_item; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.cart_item (id, quantity, created_at, updated_at, cart_id, product_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	management_system	cartitem
8	management_system	cartmanagement
9	management_system	order
10	management_system	orderitem
11	management_system	productbookcategory
12	management_system	productbookdetails
13	authtoken	token
14	authtoken	tokenproxy
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-23 07:39:29.050984+00
2	auth	0001_initial	2026-09-23 07:39:29.162194+00
3	admin	0001_initial	2026-09-23 07:39:29.19705+00
4	admin	0002_logentry_remove_auto_add	2026-09-23 07:39:29.213658+00
5	admin	0003_logentry_add_action_flag_choices	2026-09-23 07:39:29.240074+00
6	contenttypes	0002_remove_content_type_name	2026-09-23 07:39:29.272789+00
7	auth	0002_alter_permission_name_max_length	2026-09-23 07:39:29.294646+00
8	auth	0003_alter_user_email_max_length	2026-09-23 07:39:29.30491+00
9	auth	0004_alter_user_username_opts	2026-09-23 07:39:29.316862+00
10	auth	0005_alter_user_last_login_null	2026-09-23 07:39:29.331534+00
11	auth	0006_require_contenttypes_0002	2026-09-23 07:39:29.336389+00
12	auth	0007_alter_validators_add_error_messages	2026-09-23 07:39:29.350833+00
13	auth	0008_alter_user_username_max_length	2026-09-23 07:39:29.364615+00
14	auth	0009_alter_user_last_name_max_length	2026-09-23 07:39:29.375737+00
15	auth	0010_alter_group_name_max_length	2026-09-23 07:39:29.384828+00
16	auth	0011_update_proxy_permissions	2026-09-23 07:39:29.392958+00
17	auth	0012_alter_user_first_name_max_length	2026-09-23 07:39:29.401625+00
18	sessions	0001_initial	2026-09-23 07:39:29.411933+00
19	management_system	0001_initial	2026-09-23 07:57:40.047478+00
20	management_system	0002_alter_productbookcategory_table_and_more	2026-09-23 08:00:46.122969+00
21	management_system	0003_productbookdetails_pdf	2026-09-23 16:29:15.667361+00
22	authtoken	0001_initial	2026-09-24 15:06:23.238618+00
23	authtoken	0002_auto_20160226_1747	2026-09-24 15:06:23.262908+00
24	authtoken	0003_tokenproxy	2026-09-24 15:06:23.266142+00
25	authtoken	0004_alter_tokenproxy_options	2026-09-24 15:06:23.270619+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
7tovi01z0zfa9yepabaddno0kto32ga2	e30:1x9Lhh:0Liz6z1amS9_csNDE1psmn8N7E_m0FP2NXQ5oUT65yk	2026-10-07 12:04:01.511547+00
1imfjyqtrc2ypi0whcsm8xmjxj624d0z	.eJxVjMsOwiAQRf-FtSFlijxcuu83kJkBpGogKe3K-O_apAvd3nPOfYmA21rC1tMS5iguwojT70bIj1R3EO9Yb01yq-syk9wVedAupxbT83q4fwcFe_nWRNl40IB0zqOKDkfFwF77qC3jkAdPMAJ4m1xGbTJHa9FYAs1KOzbi_QHxeDgJ:1xA4Rw:kabysH1pIi_8ovx2Y9Kll8lDceCFpHLfSUYtzz_4I0I	2026-10-09 11:50:44.125119+00
\.


--
-- Data for Name: order_item; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.order_item (id, quantity, price, created_at, order_id, product_id) FROM stdin;
1	1	42.50	2026-09-24 11:05:32.101637+00	1	3
2	1	22.00	2026-09-24 11:05:32.104794+00	1	4
3	1	27.00	2026-09-24 11:07:19.604241+00	2	8
4	1	22.00	2026-09-24 11:07:19.606196+00	2	4
5	1	16.50	2026-09-24 11:12:19.335117+00	3	5
6	1	22.00	2026-09-24 11:12:19.337213+00	3	4
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.orders (id, order_number, total_amount, status, created_at, updated_at, user_id) FROM stdin;
2	ORD-20260924-49A33D	49.00	PENDING	2026-09-24 11:07:19.602017+00	2026-09-24 11:07:19.602026+00	2
3	ORD-20260924-643128	38.50	DELIVERED	2026-09-24 11:12:19.334043+00	2026-09-24 11:23:29.9324+00	2
1	ORD-20260924-5F0869	64.50	CANCELLED	2026-09-24 11:05:32.100614+00	2026-09-24 11:23:33.80785+00	2
\.


--
-- Data for Name: product_category; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.product_category (id, choice) FROM stdin;
2	History
3	Arts
4	Science & Mathematics
5	Health & Wellness
6	Textbooks
7	Fiction
8	Science Fiction
9	Fantasy
10	Mystery
11	Thriller
12	Romance
13	Historical Fiction
14	Horror
15	Adventure
16	Crime
17	Biography
18	Autobiography
19	Self-Help
20	Personal Development
21	Business
22	Finance
23	Economics
24	Management
25	Marketing
26	Computer Science
27	Programming
28	Web Development
29	Data Science
30	Artificial Intelligence
31	Machine Learning
32	Cybersecurity
33	Networking
34	Database
35	Mathematics
36	Physics
37	Chemistry
38	Biology
39	Medicine
40	Health & Fitness
41	Psychology
42	Philosophy
43	Politics
44	Law
45	Education
46	Travel
47	Cooking
48	Poetry
50	Children's Books
51	Young Adult
52	Comics & Graphic Novels
53	Art
54	Music
55	Religion & Spirituality
56	Reference
57	Test
1	Science
58	Back-End Engineering
49	Drama
59	Front-End Engineering
\.


--
-- Data for Name: product_details; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.product_details (id, isbn, title, author, description, price, publication_year, image, total_copies, available_copies, is_active, created_at, updated_at, category_id, pdf) FROM stdin;
5	9780307588371	Gone Girl	Gillian Flynn	A psychological thriller detailing the mysterious disappearance of Amy Dunne and the secrets that unravel behind a seemingly perfect marriage.	16.50	2012	images/books/nature.jpg	20	14	t	2026-09-23 18:38:48.8604+00	2026-09-24 11:12:19.335994+00	7	books/pdf/dummy_5_pkCLPxx.pdf
7	9780441172719	Dune	Frank Herbert	Set on the desert planet Arrakis, Dune tells the story of Paul Atreides as he navigates political betrayal, spice trade rivalry, and desert survival.	18.99	1965	images/books/1020-600x800.jpg	22	19	t	2026-09-24 10:25:48.17403+00	2026-09-24 10:25:48.174042+00	7	books/pdf/AI__Tech_Intern_Assessment_Test.pdf
3	9780135957059	The Pragmatic Programmer	Andrew Hunt & David Thomas	A guide detailing software engineering best practices, career development, and code architecture.	42.50	1999	images/books/tea_cup.jpg	10	8	t	2026-09-23 18:33:38.315648+00	2026-09-24 11:05:32.103791+00	26	books/pdf/dummy_4.pdf
4	9780062316097	Sapiens: A Brief History of Humankind	Yuval Noah Harari	An exploration of human history from the evolution of archaic human species in the Stone Age up to twenty-first-century political structures.	22.00	2014	images/books/tiger.jpg	35	22	t	2026-09-23 18:35:37.228712+00	2026-09-24 11:12:19.337927+00	8	books/pdf/dummy_5.pdf
1	9780140437713	The Adventures of Sherlock Holmes	Arthur Conan Doyle	A collection of twelve short stories featuring the famous detective Sherlock Holmes and his companion Dr. John Watson, investigating mysteries across Victorian London.	14.99	1892	images/books/1010-600x800.jpg	25	17	f	2026-09-23 16:56:33.706049+00	2026-09-24 17:33:29.006631+00	1	books/pdf/dummy.pdf
10	9780132350884	Clean Code	Robert C. Martin	A handbook of agile software craftsmanship.	599.00	1973		15	10	t	2026-09-24 15:57:05.461352+00	2026-09-25 06:12:55.981177+00	1	
6	9780345331359	Cosmos	Carl Sagan	An exploration of fourteen billion years of cosmic evolution, science philosophy, and humanity's place in the universe.	21.99	1980	images/books/nature_1.jpg	12	6	t	2026-09-23 18:41:04.684901+00	2026-09-24 11:03:41.322871+00	7	books/pdf/dummy_5_baAPsx3.pdf
8	9780735211292	Atomic Habits	James Clear	A practical framework for self-improvement that teaches how small daily habits compound into remarkable long-term life results.	27.00	2018	images/books/1027-600x800.jpg	35	25	t	2026-09-24 10:33:08.733627+00	2026-09-24 11:07:19.60494+00	7	books/pdf/dummy_fcraO3m.pdf
9	9780134685991	Artificial Intelligence: A Modern Approach	Stuart Russell & Peter Norvig	The comprehensive textbook on the theory, mathematical foundations, and application of artificial intelligence and machine learning.	89.99	2020	images/books/1069-600x800.jpg	15	15	t	2026-09-24 10:34:28.998052+00	2026-09-25 06:13:32.569504+00	13	books/pdf/dummy_URXUWne.pdf
2	9780451524935	1984	George Orwell	A dystopian novel setting out a grim vision of a totalitarian future where critical thought is suppressed.	12.99	1949	images/books/1025-600x800.jpg	15	10	t	2026-09-23 18:11:33.816129+00	2026-09-25 06:14:06.57643+00	1	books/pdf/dummy_2.pdf
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 56, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 6, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: book_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.book_category_id_seq', 59, true);


--
-- Name: cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.cart_id_seq', 2, true);


--
-- Name: cart_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.cart_item_id_seq', 18, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 14, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 25, true);


--
-- Name: order_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.order_item_id_seq', 6, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.orders_id_seq', 3, true);


--
-- Name: product_book_details_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.product_book_details_id_seq', 10, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: product_category book_category_choice_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT book_category_choice_key UNIQUE (choice);


--
-- Name: product_category book_category_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_category
    ADD CONSTRAINT book_category_pkey PRIMARY KEY (id);


--
-- Name: cart_item cart_item_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_item_pkey PRIMARY KEY (id);


--
-- Name: cart cart_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_pkey PRIMARY KEY (id);


--
-- Name: cart cart_user_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: order_item order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_pkey PRIMARY KEY (id);


--
-- Name: orders orders_order_number_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_order_number_key UNIQUE (order_number);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: product_details product_book_details_isbn_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT product_book_details_isbn_key UNIQUE (isbn);


--
-- Name: product_details product_book_details_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT product_book_details_pkey PRIMARY KEY (id);


--
-- Name: product_details product_book_details_title_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT product_book_details_title_key UNIQUE (title);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: book_category_choice_a4c6ef15_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX book_category_choice_a4c6ef15_like ON public.product_category USING btree (choice varchar_pattern_ops);


--
-- Name: cart_item_cart_id_157ecf5f; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX cart_item_cart_id_157ecf5f ON public.cart_item USING btree (cart_id);


--
-- Name: cart_item_product_id_17acb13c; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX cart_item_product_id_17acb13c ON public.cart_item USING btree (product_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: order_item_order_id_0ca9e92e; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX order_item_order_id_0ca9e92e ON public.order_item USING btree (order_id);


--
-- Name: order_item_product_id_62a1cc4c; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX order_item_product_id_62a1cc4c ON public.order_item USING btree (product_id);


--
-- Name: orders_order_number_fdca857f_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX orders_order_number_fdca857f_like ON public.orders USING btree (order_number varchar_pattern_ops);


--
-- Name: orders_user_id_7e2523fb; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX orders_user_id_7e2523fb ON public.orders USING btree (user_id);


--
-- Name: product_book_details_category_id_42b5131f; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX product_book_details_category_id_42b5131f ON public.product_details USING btree (category_id);


--
-- Name: product_book_details_isbn_a9d86456_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX product_book_details_isbn_a9d86456_like ON public.product_details USING btree (isbn varchar_pattern_ops);


--
-- Name: product_book_details_title_ef400bb4_like; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX product_book_details_title_ef400bb4_like ON public.product_details USING btree (title varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_item cart_item_cart_id_157ecf5f_fk_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_item_cart_id_157ecf5f_fk_cart_id FOREIGN KEY (cart_id) REFERENCES public.cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_item cart_item_product_id_17acb13c_fk_product_book_details_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_item_product_id_17acb13c_fk_product_book_details_id FOREIGN KEY (product_id) REFERENCES public.product_details(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart cart_user_id_1361a739_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_user_id_1361a739_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_item order_item_order_id_0ca9e92e_fk_orders_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_order_id_0ca9e92e_fk_orders_id FOREIGN KEY (order_id) REFERENCES public.orders(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_item order_item_product_id_62a1cc4c_fk_product_book_details_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_product_id_62a1cc4c_fk_product_book_details_id FOREIGN KEY (product_id) REFERENCES public.product_details(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: orders orders_user_id_7e2523fb_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_user_id_7e2523fb_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: product_details product_book_details_category_id_42b5131f_fk_book_category_id; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.product_details
    ADD CONSTRAINT product_book_details_category_id_42b5131f_fk_book_category_id FOREIGN KEY (category_id) REFERENCES public.product_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict KvytyS4b8dUBVBtSaxH0R9Utnvel5A4NUgwbesDSJuQ8o7MftupEA588xypkEpQ

