# Generated by Django 6.1.1 on 2026-09-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productbookcategory',
            table='product_category',
        ),
        migrations.AlterModelTable(
            name='productbookdetails',
            table='product_details',
        ),
    ]
