# Generated by Django 6.1.1 on 2026-09-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0002_alter_productbookcategory_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbookdetails',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='books/pdf/'),
        ),
    ]
